package com.vscodroid.setup

import com.vscodroid.BuildConfig
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNotNull
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir
import java.io.File
import java.security.MessageDigest

/**
 * Reading a release's digest manifest, and hashing what was downloaded.
 *
 * These are the two decisions behind the check that HTTP-delivered toolchains
 * had none of. Both are separated from the network so they can be checked
 * against inputs a test chooses; the wiring that calls them is covered
 * end-to-end in [ToolchainDigestInstallTest], over a loopback server.
 *
 * The risk here runs one way and it is worth naming before the assertions. A
 * manifest reader that answers null too often costs a refused install, which a
 * re-release fixes. One that answers a digest the manifest did not really state
 * for this file defeats the whole check, and defeats it silently, because the
 * comparison downstream then passes and the archive is extracted, chmodded and
 * symlinked into `usr/`.
 */
class ToolchainDigestTest {

    @TempDir
    lateinit var dir: File

    /** A real SHA-256, and a second one that differs from it. */
    private val goDigest = "9f2fcc7c90de090d6b87cd7e9718c1ea6cb21118fc2d5de9f97e5db6ac1e9c10"
    private val rubyDigest = "1a0d0b6b9d6d7f6e5c4b3a2918273645ba0987654321fedcba9876543210abcd"

    // ── digestFromManifest ───────────────────────────────────────────────

    @Test
    fun `finds the digest for the named file`() {
        // The positive control. Without it every refusal below would also pass
        // against a reader that returns null unconditionally.
        val manifest = "$goDigest  toolchain_go.zip\n$rubyDigest  toolchain_ruby.zip\n"

        assertEquals(goDigest, digestFromManifest(manifest, "toolchain_go.zip"))
        assertEquals(rubyDigest, digestFromManifest(manifest, "toolchain_ruby.zip"))
    }

    @Test
    fun `a file the manifest does not name has no digest`() {
        // What a release that packaged a ZIP and forgot its digest produces.
        // Answering anything but null here is the failure mode being removed.
        assertNull(digestFromManifest("$goDigest  toolchain_go.zip\n", "toolchain_java.zip"))
    }

    @Test
    fun `an empty manifest yields no digest`() {
        assertNull(digestFromManifest("", "toolchain_go.zip"))
        assertNull(digestFromManifest("\n\n   \n", "toolchain_go.zip"))
    }

    @Test
    fun `binary-mode entries are read`() {
        // sha256sum writes "*name" when hashing in binary mode, which is what
        // `sha256sum -b` and several ports do by default. Dropping the
        // removePrefix("*") leaves every such manifest unreadable and every
        // install refused.
        assertEquals(goDigest, digestFromManifest("$goDigest *toolchain_go.zip\n", "toolchain_go.zip"))
    }

    @Test
    fun `an entry written with a path is matched by its filename`() {
        // The build hashes files under toolchain-zips/ while the release serves
        // them flattened, so the manifest can legitimately carry a path. Losing
        // substringAfterLast('/') refuses every toolchain on a release whose
        // manifest was generated from a directory.
        assertEquals(
            goDigest,
            digestFromManifest("$goDigest  ./toolchain-zips/toolchain_go.zip\n", "toolchain_go.zip"),
        )
    }

    @Test
    fun `blank lines and comments are ignored`() {
        val manifest = """
            # generated by release.yml

            $goDigest  toolchain_go.zip

        """.trimIndent()

        assertEquals(goDigest, digestFromManifest(manifest, "toolchain_go.zip"))
    }

    @Test
    fun `a digest written in upper case is normalised`() {
        // Comparison downstream is case-insensitive too, so this is belt and
        // braces rather than the only guard -- but a reader that returns mixed
        // case makes that downstream leniency load-bearing without saying so.
        assertEquals(goDigest, digestFromManifest("${goDigest.uppercase()}  toolchain_go.zip\n", "toolchain_go.zip"))
    }

    @Test
    fun `a first field that is not a sha256 is not treated as one`() {
        // Two ways a line can look like an entry without being one: a shorter
        // hash from a different algorithm, and a line the read bound cut in
        // half. Neither may be handed on as a digest -- the second is why the
        // bounded read in fetchManifest is safe.
        assertNull(digestFromManifest("d41d8cd98f00b204e9800998ecf8427e  toolchain_go.zip\n", "toolchain_go.zip"))
        assertNull(digestFromManifest("${goDigest.take(40)}  toolchain_go.zip\n", "toolchain_go.zip"))
        assertNull(digestFromManifest("not-a-digest  toolchain_go.zip\n", "toolchain_go.zip"))
    }

    @Test
    fun `a name with no digest beside it yields nothing`() {
        assertNull(digestFromManifest("toolchain_go.zip\n", "toolchain_go.zip"))
    }

    @Test
    fun `a manifest naming one file twice with different digests is refused`() {
        // A manifest that cannot make up its mind is not evidence. Resolving it
        // by taking the first or the last would let whichever entry an attacker
        // could append decide the answer.
        val manifest = "$goDigest  toolchain_go.zip\n$rubyDigest  toolchain_go.zip\n"

        assertNull(digestFromManifest(manifest, "toolchain_go.zip"))
    }

    @Test
    fun `a manifest repeating the same entry is not ambiguous`() {
        // The other half: identical duplicates say one thing, so refusing them
        // would be refusing a manifest that is merely redundant.
        val manifest = "$goDigest  toolchain_go.zip\n$goDigest  ./toolchain-zips/toolchain_go.zip\n"

        assertEquals(goDigest, digestFromManifest(manifest, "toolchain_go.zip"))
    }

    @Test
    fun `a prefix of the wanted name does not match it`() {
        // Names are compared whole. Matching on prefix or containment would let
        // toolchain_go.zip.old vouch for toolchain_go.zip.
        assertNull(digestFromManifest("$goDigest  toolchain_go.zip.old\n", "toolchain_go.zip"))
        assertNull(digestFromManifest("$goDigest  go.zip\n", "toolchain_go.zip"))
    }

    // ── sha256Of ─────────────────────────────────────────────────────────

    @Test
    fun `hashes a known vector`() {
        // The published SHA-256 of "abc", not a value produced by this code.
        // A test that hashed with the same helper it is checking would agree
        // with any implementation, including a broken one.
        val file = File(dir, "abc").apply { writeBytes("abc".toByteArray()) }

        assertEquals(
            "ba7816bf8f01cfea414140de5dae2223b00361a396177a9cb410ff61f20015ad",
            sha256Of(file),
        )
    }

    @Test
    fun `hashes an empty file to the known empty digest`() {
        val file = File(dir, "empty").apply { writeBytes(ByteArray(0)) }

        assertEquals(
            "e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855",
            sha256Of(file),
        )
    }

    @Test
    fun `hashes a payload larger than one read buffer`() {
        // The toolchains are up to 179 MB and the helper streams them in 64 KB
        // chunks, so the chunking loop is the part that matters. Checked
        // against a one-shot digest of the same bytes -- a different route
        // through MessageDigest, so a loop that dropped or repeated a chunk
        // shows up here rather than agreeing with itself.
        val bytes = ByteArray(300_000) { (it % 251).toByte() }
        val file = File(dir, "large.zip").apply { writeBytes(bytes) }

        val oneShot = MessageDigest.getInstance("SHA-256").digest(bytes)
            .joinToString("") { "%02x".format(it) }

        assertEquals(oneShot, sha256Of(file))
    }

    @Test
    fun `a changed byte changes the digest`() {
        // States the property the whole check rests on, so that a helper
        // returning a constant cannot pass the vectors above by coincidence.
        val a = File(dir, "a.zip").apply { writeBytes(byteArrayOf(1, 2, 3, 4)) }
        val b = File(dir, "b.zip").apply { writeBytes(byteArrayOf(1, 2, 3, 5)) }

        org.junit.jupiter.api.Assertions.assertNotEquals(sha256Of(a), sha256Of(b))
    }

    // ── manifestUrlFor ───────────────────────────────────────────────────

    @Test
    fun `the manifest is looked for beside the zip`() {
        assertEquals(
            "https://github.com/rmyndharis/VSCodroid/releases/latest/download/toolchains.sha256",
            manifestUrlFor(
                "https://github.com/rmyndharis/VSCodroid/releases/latest/download/toolchain_go.zip"
            ),
        )
    }

    @Test
    fun `every registered toolchain resolves to the same manifest`() {
        // The reason the URL is derived rather than written down twice. If two
        // toolchains ever resolved to different manifests, one release could
        // vouch for one of them and not the other with nothing failing.
        val manifests = ToolchainRegistry.available
            .mapNotNull { it.downloadUrl }
            .map { manifestUrlFor(it) }
            .toSet()

        assertEquals(1, manifests.size, "registered toolchains disagree about the manifest: $manifests")
    }
}

/**
 * Resolving `latest` to one concrete release, so the manifest and the payload
 * cannot come from two.
 *
 * The risk here runs one way, and it is the opposite of the digest reader's. A
 * resolver that answers null too often costs the old behaviour, which is a rare
 * race that fails closed and succeeds on retry. One that answers a plausible but
 * wrong URL 404s every toolchain for everyone, so each function below refuses
 * anything it does not fully recognise rather than pasting it into a URL.
 *
 * The redirect shape these are written against was measured on 2026-08-16:
 * `releases/latest` answers `302` to `releases/tag/<tag>` in one hop, while
 * `releases/latest/download/<asset>` takes two and ends at a signed CDN address
 * that carries no tag at all.
 */
class LatestReleasePinningTest {

    private val zip = "https://github.com/rmyndharis/VSCodroid/releases/latest/download/toolchain_go.zip"

    @Test
    fun `the release URL is derived from an asset URL`() {
        assertEquals(
            "https://github.com/rmyndharis/VSCodroid/releases/latest",
            latestReleaseUrlFor(zip),
        )
    }

    @Test
    fun `a URL that does not go through latest resolves to nothing`() {
        // Already pinned, so there is nothing to resolve and the caller keeps
        // what it has.
        assertNull(
            latestReleaseUrlFor(
                "https://github.com/rmyndharis/VSCodroid/releases/download/v1.0.0/toolchain_go.zip"
            )
        )
    }

    @Test
    fun `the tag is read out of the redirect GitHub actually sends`() {
        assertEquals(
            "v1.0.0",
            releaseTagFromLocation("https://github.com/rmyndharis/VSCodroid/releases/tag/v1.0.0"),
        )
        // The server release tag is not v-prefixed, and is the one this has to
        // keep out of the app channel rather than mis-parse.
        assertEquals(
            "server-1.133.0",
            releaseTagFromLocation("https://github.com/rmyndharis/VSCodroid/releases/tag/server-1.133.0"),
        )
    }

    @Test
    fun `a redirect that names no usable tag is refused`() {
        // Kills a parser that takes whatever follows the marker. Each of these
        // would build a URL that 404s, and the fallback is strictly better.
        assertNull(releaseTagFromLocation("https://github.com/o/r/releases"))
        assertNull(releaseTagFromLocation("https://github.com/o/r/releases/tag/"))
        assertNull(releaseTagFromLocation("https://github.com/o/r/releases/tag/a b"))
        assertNull(releaseTagFromLocation("https://github.com/o/r/releases/tag/../../evil"))
    }

    @Test
    fun `pinning replaces latest with the tag and keeps the asset`() {
        assertEquals(
            "https://github.com/rmyndharis/VSCodroid/releases/download/v1.0.0/toolchain_go.zip",
            pinnedAssetUrl(zip, "v1.0.0"),
        )
    }

    @Test
    fun `pinning refuses what it does not recognise`() {
        assertNull(pinnedAssetUrl("https://example.test/some/other/path.zip", "v1.0.0"))
        assertNull(pinnedAssetUrl(zip, "not a tag"))
        // An asset that is itself a path was never the shape this is for, and
        // pasting it would name something else entirely.
        assertNull(
            pinnedAssetUrl(
                "https://github.com/o/r/releases/latest/download/nested/x.zip",
                "v1.0.0",
            )
        )
    }

    @Test
    fun `pinning the ZIP pins the manifest beside it`() {
        // The invariant the whole change rests on. Only the ZIP URL is resolved;
        // the manifest is derived from it afterwards, so if this ever stopped
        // holding the two requests would silently address different releases
        // again and nothing else would notice.
        val pinned = pinnedAssetUrl(zip, "v1.1.0")!!

        assertEquals(
            "https://github.com/rmyndharis/VSCodroid/releases/download/v1.1.0/toolchains.sha256",
            manifestUrlFor(pinned),
        )
    }

    @Test
    fun `every registered toolchain can be pinned to one release`() {
        // The registry-wide version of the test above: one resolution has to
        // serve every entry, or a single install could pin while another does not.
        val pinned = ToolchainRegistry.available
            .mapNotNull { it.downloadUrl }
            .map { pinnedAssetUrl(it, "v1.1.0") }

        assertEquals(emptyList<String?>(), pinned.filter { it == null }, "a registered toolchain could not be pinned")
        assertEquals(
            1,
            pinned.filterNotNull().map { manifestUrlFor(it) }.toSet().size,
            "pinned toolchains disagree about the manifest",
        )
    }

    // -- appReleaseTag ----------------------------------------------------

    @Test
    fun `an install reaches the release its own version names`() {
        // The case this exists for, measured 2026-08-19 while `latest` named
        // v1.1.0: an installed v1.0.0 still offers Go, v1.1.0 does not publish
        // that ZIP because the entry was retired, and the two URLs below differ
        // by 404 against 200. The literal is the one that answers 200.
        val go = "https://github.com/rmyndharis/VSCodroid/releases/latest/download/toolchain_go.zip"

        val pinned = pinnedAssetUrl(go, appReleaseTag("1.0.0")!!)

        assertEquals(
            "https://github.com/rmyndharis/VSCodroid/releases/download/v1.0.0/toolchain_go.zip",
            pinned,
        )
    }

    @Test
    fun `a debug build belongs to the release its source does`() {
        // `versionNameSuffix` is a build-type detail; no release is ever tagged
        // with it. Left in, every debug build would probe a tag that does not
        // exist and quietly fall back to `latest`, which is the behaviour this
        // replaces.
        assertEquals("v1.1.0", appReleaseTag("1.1.0-debug"))
    }

    @Test
    fun `a version that cannot name a tag resolves to nothing`() {
        // Null is the fallback signal, so it has to be reachable. A version
        // carrying a slash would otherwise be pasted into a URL naming
        // something else entirely.
        assertNull(appReleaseTag(""))
        assertNull(appReleaseTag("1.1.0/../../etc"))
        assertNull(appReleaseTag("1.1 .0"))
    }

    @Test
    fun `this build's own version name yields a tag the pinner accepts`() {
        // The cases around this one pass literals, which checks the function and
        // not the build. This one reads the value the app will actually hand it.
        //
        // Worth stating what it protects, because the failure is silent, and worth
        // separating two failures the same sentence used to conflate. A versionName
        // carrying a character `TAG_CHARS` refuses makes `appReleaseTag` answer
        // null. A `versionNameSuffix` it does not strip does not: `TAG_CHARS`
        // accepts `-`, so the function returns a tag WITH the suffix, no release
        // carries that tag, and the probe 404s. Both end the same way, with
        // `pinLatest` falling back to `latest` forever and a payload quietly
        // coming from the wrong release, and neither reports anything.
        //
        // The second assertion looks for the word `debug` rather than banning `-`
        // outright, because this project has shipped prerelease tags (`v0.1.0-alpha`,
        // `v0.2.2-m6`) and a legitimate one must not turn the suite red. It is a
        // guard against one word and says so: a build type marked some other way
        // would pass it. `endsWith("-debug")` was tried first and is worse than
        // useless, since `removeSuffix` strips exactly that string, so the only
        // suffixes that survive to be asserted on are the ones it does not match.
        //
        // What runs this is the debug variant, so the value read here is the
        // release versionName plus "-debug" and suffix stripping is the half it
        // proves. The un-suffixed form is proved beside it, by literal, in
        // `an install reaches the release its own version names`.
        //
        // Not because a release unit test task does not exist. It does, and it
        // runs: `testReleaseUnitTest` produced 192 result files, 1221 tests and
        // zero failures on 2026-08-20. `testBuildType` selects the INSTRUMENTED
        // component; unit test tasks are generated for every build type. What is
        // true is narrower and is about CI rather than AGP: no workflow invokes
        // it. Measured, and scoped away from this comment so it does not count
        // itself: `git grep -c testReleaseUnitTest -- .github scripts '*.kts'`
        // is 0, while the same search for the debug task is 5, of which two are
        // the `./gradlew testDebugUnitTest` lines in build.yml and release.yml.
        // So only a local run has ever exercised the release variant.
        //
        // Not quoted here: the literal went stale at the first version bump,
        // while the property it describes did not.
        val tag = appReleaseTag(BuildConfig.VERSION_NAME)

        assertNotNull(
            tag,
            "BuildConfig.VERSION_NAME is \"${BuildConfig.VERSION_NAME}\" and appReleaseTag " +
                "refuses it, so every install would silently resolve through `latest`. " +
                "TAG_CHARS rejects it, which means the version format itself changed: " +
                "a suffix alone does not land here, it lands in the case below.",
        )
        assertTrue(
            !tag!!.contains("debug"),
            "the tag is \"$tag\", which still carries a debug marker. No release is " +
                "tagged with one, so the probe would 404 and pinning would fall back to " +
                "`latest` permanently.",
        )
        assertNotNull(
            pinnedAssetUrl(zip, tag),
            "appReleaseTag produced \"$tag\" and pinnedAssetUrl refuses it. The two " +
                "disagree about the shape of a tag, so pinning is dead.",
        )
    }

    @Test
    fun `the tag this build names is one the pinner accepts`() {
        // The two halves are written apart and only ever meet at runtime. If
        // they disagreed about the shape of a tag, `pinnedAssetUrl` would
        // refuse every tag this produces, pinning would revert to `latest`
        // permanently, and nothing would report it: the fallback is silent by
        // design because it is also the correct answer for a dev build.
        val tag = appReleaseTag("1.1.0")!!

        val pinned = ToolchainRegistry.available
            .mapNotNull { it.downloadUrl }
            .map { pinnedAssetUrl(it, tag) }

        assertEquals(
            emptyList<String?>(),
            pinned.filter { it == null },
            "the pinner refused a tag this build would hand it",
        )
    }
}
